embeddings {
  tensor_name: "city:00527"
  metadata_path: "00527/city/metadata.tsv"
  tensor_path: "00527/city/tensors.tsv"
}
embeddings {
  tensor_name: "year:00527"
  metadata_path: "00527/year/metadata.tsv"
  tensor_path: "00527/year/tensors.tsv"
}
embeddings {
  tensor_name: "month:00527"
  metadata_path: "00527/month/metadata.tsv"
  tensor_path: "00527/month/tensors.tsv"
}
embeddings {
  tensor_name: "day:00527"
  metadata_path: "00527/day/metadata.tsv"
  tensor_path: "00527/day/tensors.tsv"
}
