embeddings {
  tensor_name: "city:01209"
  metadata_path: "01209/city/metadata.tsv"
  tensor_path: "01209/city/tensors.tsv"
}
embeddings {
  tensor_name: "year:01209"
  metadata_path: "01209/year/metadata.tsv"
  tensor_path: "01209/year/tensors.tsv"
}
embeddings {
  tensor_name: "month:01209"
  metadata_path: "01209/month/metadata.tsv"
  tensor_path: "01209/month/tensors.tsv"
}
embeddings {
  tensor_name: "day:01209"
  metadata_path: "01209/day/metadata.tsv"
  tensor_path: "01209/day/tensors.tsv"
}
