version: "3.9"

services:
  app_forecasting_car_insurance:
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
      - ../data:/workspace/data
      - ../notebooks:/workspace/notebooks
      - ../src:/workspace/src
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true